"""add_standard_answers_and_submission_audit

Revision ID: 84325e37e095
Revises: a12c32a0c7cd
Create Date: 2026-04-20 18:02:55.387112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84325e37e095'
down_revision: Union[str, None] = 'a12c32a0c7cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('submission_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('applications', sa.Column('submission_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('generated_documents', sa.Column('structured_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('user_profiles', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_profiles', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_profiles', sa.Column('work_authorization', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_profiles', sa.Column('requires_sponsorship', sa.Boolean(), nullable=True))
    op.add_column('user_profiles', sa.Column('salary_expectation_usd', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('available_from', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_profiles', sa.Column('standard_answers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'standard_answers')
    op.drop_column('user_profiles', 'available_from')
    op.drop_column('user_profiles', 'salary_expectation_usd')
    op.drop_column('user_profiles', 'requires_sponsorship')
    op.drop_column('user_profiles', 'work_authorization')
    op.drop_column('user_profiles', 'last_name')
    op.drop_column('user_profiles', 'first_name')
    op.drop_column('generated_documents', 'structured_content')
    op.drop_column('applications', 'submission_result')
    op.drop_column('applications', 'submission_method')
    op.drop_column('applications', 'submitted_at')
    # ### end Alembic commands ###
