"""initial_schema

Revision ID: cfd76b2ed274
Revises:
Create Date: 2026-04-15 02:38:52.490120

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cfd76b2ed274"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_search_cache",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("query_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("query", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("results", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_job_search_cache_query_hash"), "job_search_cache", ["query_hash"], unique=True
    )
    op.create_index(
        "ix_search_cache_lookup",
        "job_search_cache",
        ["source", "query_hash", "expires_at"],
        unique=False,
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ats_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("company_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("workplace_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description_md", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("apply_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("supports_api_apply", sa.Boolean(), nullable=False),
        sa.Column("posted_at", sa.DateTime(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "external_id", name="uq_jobs_source_external_id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "user_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("linkedin_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("github_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("portfolio_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("base_resume_md", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("base_resume_raw", sa.LargeBinary(), nullable=True),
        sa.Column("target_roles", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("target_locations", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("remote_ok", sa.Boolean(), nullable=False),
        sa.Column("seniority", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("search_keywords", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("source_cursors", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("search_active", sa.Boolean(), nullable=False),
        sa.Column("search_expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "applications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("generation_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("generation_attempts", sa.Integer(), nullable=False),
        sa.Column("match_score", sa.Float(), nullable=True),
        sa.Column("match_rationale", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("match_strengths", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("match_gaps", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["user_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "profile_id", name="uq_applications_job_profile"),
    )
    op.create_index(
        "ix_applications_dashboard",
        "applications",
        ["profile_id", "status", "match_score"],
        unique=False,
    )
    op.create_table(
        "skills",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("proficiency", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("years", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["user_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "work_experiences",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("company", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("description_md", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("technologies", postgresql.ARRAY(sa.String()), nullable=True),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["user_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "generated_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("doc_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_md", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_edited_md", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("generation_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("generated_documents")
    op.drop_table("work_experiences")
    op.drop_table("skills")
    op.drop_index("ix_applications_dashboard", table_name="applications")
    op.drop_table("applications")
    op.drop_table("user_profiles")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("jobs")
    op.drop_index("ix_search_cache_lookup", table_name="job_search_cache")
    op.drop_index(op.f("ix_job_search_cache_query_hash"), table_name="job_search_cache")
    op.drop_table("job_search_cache")
    # ### end Alembic commands ###
